[package]
name = "wifi_qr"
version = "0.1.0"
authors = ["codepitbull <jochen@codepitbull.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qrcodegen = "1.5.0"
chrono = "0.4"
rand = "0.7.3"